### PR TITLE
Ignore missing files when compressing target directories

### PR DESCRIPTION
**Pull request by majk-p**
This PR resolves https://github.com/djspiewak/sbt-github-actions/issues/60

### CODE REVIEW

**Comment by majk-p** [comment]
@djspiewak please have a look

**Review by djspiewak — APPROVED** [review]
This is great! Thank you!

**Comment by djspiewak** [comment]
@majk-p Looks like some of the workflows need to be updated with the new flag!

**Comment by majk-p** [comment]
Thanks @djspiewak! just regenerated the workflows, should work now :crossed_fingers:

**Comment by djspiewak** [comment]
I think it's actually the tests that are the problem. Specifically:

- non-existent-target
- sbt-native-thin-client
- check-and-regenerate

The easiest thing to do is probably go in and manually edit the `ci.yml` files in each to have the new flag on their `tar` invocations. You can check to make sure it's working correctly by running `sbt scripted`

**Comment by majk-p** [comment]
Sorry, I should've tested it locally. The `ci.yml` files are now adjusted, `sbt scripted` passed with no issues. It should be ready now.

**Comment by majk-p** [comment]
Looks like `macos-latest` failed due to `tar: Option --ignore-failed-read is not supported`. Doesn't macos go with regular gnu tar? is it just the workflow or does it break this way on desktop?

**Comment by djspiewak** [comment]
> Doesn't macos go with regular gnu tar? is it just the workflow or does it break this way on desktop?

Seems to be that way on desktop as well. One way we can work around this is to just install our own `tar`.

**Comment by kubukoz** [comment]
I'm on macos and my tar is bsdtar, it does complain about the flag. Gnutar recognizes it.

**Comment by armanbilge** [comment]
Just saw this—I actually ran into this problem with feral and my solution was to `mkdir -p` all the targets instead, before the compressing step.

```scala
ThisBuild / githubWorkflowGeneratedUploadSteps ~= { steps =>
  val mkdirStep = steps.headOption match {
    case Some(WorkflowStep.Run(command :: _, _, _, _, _, _)) =>
      WorkflowStep.Run(
        commands = List(command.replace("tar cf targets.tar", "mkdir -p")),
        name = Some("Make target directories")
      )
    case _ => sys.error("Can't generate make target dirs workflow step")
  }
  mkdirStep +: steps
}
```
https://github.com/typelevel/feral/blob/579409b9e228854ba6ff3d8033cd5baa71793f4a/build.sbt#L45

**Comment by mdedetrich** [comment]
@armanbilge Should we aim to get this merged or is there some additional work that needs to be done that I am missing?

**Comment by armanbilge** [comment]
@mdedetrich unfortunately the fix in this PR doesn't work. You should port my fix from sbt-typelevel that I mentioned above.

**Comment by mdedetrich** [comment]
@armanbilge Thanks for the reply, I will close this PR then and we can reimplement the proper fix separately.

**Pull request closed without merging**
