### PR TITLE
Add global permissions

### PR DESCRIPTION
**Pull request by mdedetrich**
PR adds the permissions section for generated workflow file.

### CODE REVIEW

**Comment by mdedetrich** [comment]
So the windows tests seem to be failing but I am not sure if this related?

**Comment by mdedetrich** [comment]
So after looking at this again I have updated the PR with the following improvements

* The `permissions` is actually follows a schema (see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview) so I rather than using a `Map[String, String]` it now uses a proper ADT similar to other settings in github-workflow-actions
  * The only thing I am unsure of is the `Permissions.None` which maps to `permissions: {}`. I think that having the `Permissions.None` because its the same as `Permissions.Specify(Map.empty)` but I don't know if github actions and/or yaml treats `permissions: ` same as `permissions: {}`. For similar reasons it may make sense to throw an error if an empty `Map` is passed to `Permissions.Specify`
* Permissions can also be specified on workflow steps (see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#assigning-permissions-to-a-specific-job) so I did the necessary changes there.

**Comment by mdedetrich** [comment]
@djspiewak Would ie bt possible to have a look at this?

**Comment by TonioGela** [comment]
> @djspiewak Would it be possible to have a look at this?

@djspiewak IMHO this pr has a huge value, and it's a feature that I'll love too

**Comment by mdedetrich** [comment]
@eed3si9n You mind looking at this?

**Review by eed3si9n — COMMENTED** [review]
Overall LGTM. if this passes the CI, I'd merge?

**Comment by mdedetrich** [comment]
Yup! I think the CI issues are unrelated but if needed I can look into it (I remember this project had windows related CI problems).

**Comment by TonioGela** [comment]
> So from what I can see @djspiewak doesn't seem to have capacity/time to properly take care of this project hence why I made #117

It was moved! Awesome :D

**Comment by mdedetrich** [comment]
@eed3si9n I will go ahead and merge this PR, just rebasing it now with the removal of the Windows in CI just to do a last minute sanity check to see it passes CI.

**Pull request merged**
