### PR TITLE
add convenience method for Zulu JDKs

### PR DESCRIPTION
**Pull request by SethTisue**
since I can `JavaSpec.temurin`, I would like to be able to `JavaSpec.zulu` as well

### CODE REVIEW

**Comment by SethTisue** [comment]
ha, CI is failing because of the same issue that brought me here in the first place, namely actions/setup-java#625 — macOS-latest doesn't offer `temurin@8` anymore, you have to `zulu@8`

**Comment by SethTisue** [comment]
not sure how we want to handle this. do we want the entire plugin to now default to `zulu@8` instead of `temurin@8`? or should we only default to zulu on MacOS specifically? 🤷

**Comment by eed3si9n** [comment]
I've default everything to `zulu@8` in https://github.com/sbt/sbt-github-actions/pull/187

**Comment by SethTisue** [comment]
superseded by #187, thank you Eugene!

**Pull request closed without merging**
