### PR TITLE
Bump checkout action

### PR DESCRIPTION
**Pull request by exoego**
Ref https://github.com/actions/checkout/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by mcanlas** [comment]
Pretty much the change I was going to pitch. Helps avoid "this mechanism is deprecated" errors that are showing up in GHA runs, but are outside of the user's control.

Similarly, the `cache` action suffers from the same problem. #119 attempts to solve it another way (by introducing a new key). Should that also be done here instead? Personal opinion, we should just upgrade both, haha

I wonder though if having the older versions available is important due to let's say organizations using versions of GitHub Enterprise that don't match what's deployed on GitHub.com (and therefore don't have the upgraded actions available)

**Comment by mcanlas** [comment]
This also unlocks #104, using a first class caching step from the java action (new feature) vs the hand rolled cache step (current implementation)

**Review by eed3si9n — APPROVED** [review]
Thanks @exoego! LGTM

**Comment by eed3si9n** [comment]
Looks like this was fixed in https://github.com/sbt/sbt-github-actions/pull/133

**Pull request closed without merging**
