### PR TITLE
Add attestations permission scope

### PR DESCRIPTION
**Pull request by esamson**
See: https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by mrdziuban** [comment]
Hey @eed3si9n any chance you could cut a new release with this included? I'm hoping to use this in my build. Thanks in advance!

**Comment by eed3si9n** [comment]
Done - https://github.com/sbt/sbt-github-actions/releases/tag/v0.25.0

**Comment by mrdziuban** [comment]
Thank you!

**Pull request merged**
