### PR TITLE
Calculate snapshot version properly

### PR DESCRIPTION
**Pull request by mdedetrich**
Taken from https://github.com/sbt/sbt-osgi/blob/d10f2ed8129f474ec6d4eeffa34a7ab3c0d4f091/build.sbt#L6-L20

### CODE REVIEW

**Comment by mdedetrich** [comment]
@eed3si9n If you have the time do you mind quickly reviewing this so we don't have to manually set the snapshot version again when I publish.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by eed3si9n** [comment]
Maybe we should add this code to sbt-dynver itself since all sbt plugins need it.

**Comment by mdedetrich** [comment]
> Maybe we should add this code to sbt-dynver itself since all sbt plugins need it.

I can file an issue for it since I can see arguments back and forth on this

**Comment by mdedetrich** [comment]
> Maybe we should add this code to sbt-dynver itself since all sbt plugins need it.

@eed3si9n Issue created at https://github.com/sbt/sbt-dynver/issues/277

**Pull request merged**
